#!/usr/bin/env bash

if [ "$#" -gt 1 ]; then
    echo "error: to many arguments"
    exit 1
fi

if [ "$#" -lt 1 ]; then
    echo "error: must supply post name"
    exit 1
fi

NAME=`echo $1 | sed -e 's/ /-/g'`
MD_FILE=$NAME.md

mkdir -p images/$NAME

echo "created directory: images/$NAME"

echo "---" >> $MD_FILE
echo "title: $1" >> $MD_FILE
echo "tags:" >> $MD_FILE
echo "  - tag" >> $MD_FILE
echo "date: MM-DD-YYYY" >> $MD_FILE
echo "summary: summary" >> $MD_FILE
echo "---" >> $MD_FILE

echo "created file: $NAME.md"
